### ISSUE TITLE
I hate to do this.

### ISSUE THREAD

**Issue by chmac** [Trustroots/nostroots#14]
Post by @zweifeln

I hate to do this.

I love open source. I love the sharing economy. (Though I don't really believe in the "gift" economy. Gift and economy doesn't go together. But that's beside the point.)

Every de-central approach; every maintained open source project has someone (or a rather small group of people) who take care of it. Sometimes they have a business model (like my employer does), sometimes these people have a different form of income and do it as their hobby. That's great. Sometimes these people will stop maintaining things and then half the internet may break. That's bad but it is how it has been the past 30 years.
I strongly believe it is very helpful to acknowledge that before going forward with any decentralizing idea.

Someone is actually in charge.
Someone needs to write the code and maintain it. Install updates and keep the servers running. Yes, software can update itself - but only as long as the updating part of the software itself works all fine. Software the harddrives need to be changed and sometimes software just breaks. Then there is need for someone who knows what's happening. So we *rely* on them.
That is the case no matter how good a programmer one might be. If you didn't work with that software, you don't know the libraries and frameworks.
We're having this topic here on Github. A platform owned (and maintained) by microsoft.
The only really free, decentralized software widely used out there … is e-mail. But who of you actually runs their own e-mail server? (I don't. It's too much pain.)
The point cannot be to be totally independent. Yes, that sounds nice but in reality it means, you are alone.
The point is *trust*. The thing that is already in our name. Some people have the knowledge and willpower to develop software and run it. Others will trust them and use it. That is okay. And that means, the people not running the software will trust their platform. Or not - then they will leave the platform.
Similar to how not every human on earth is making their own bread. Most of us are just buying it in a bakery. (Or don't eat bread). It is not sustainable for everyone to make their own bread. And certainly not practicable for everyone to grow their own grain.

We rely on people not on software. That is a good thing. Let's acknowledge that.
When we do that, we can go forward and make some system that is easier to maintain and better usable to more people - also non tech-people.
Running decentralized software is - unfortunately - not actually decentralized. No matter how easy it seems to tech people. It may seem easy for us who we are comfortable using Github. But it actually is quite elite. Most people I have met traveling the past 8 weeks don't know what Github is.

The point is not the software. The point is how to make it sustainable. How to have a community that is trusting each other and how that spirit might continue even when central people step back for whatever reasons. There are lots of good reasons. So often people get pressured into keeping a central role as it all would fall apart if they step back. But maybe they got sick or take care of sick people or children or maybe they are just tired after doing it for so long and actually just wanna travel themselves and enjoy live.
The the hard question is: how to keep things running. How to make sure the community has enough trusted people to step in if someone steps back. How to develop and maintain a beautiful community.
That is more a philosophical than a technical question but that is the central question.

_Originally posted by @zweifeln in https://github.com/Trustroots/nostroots/issues/11#issuecomment-1943260335_

**Comment by guaka** [comment]
The person who kept a very "central role" in Trustroots stepped down.  I happened to be the only person with enough access, which I shared with 2 more people.

*How to develop and maintain a beautiful community [who can keep it going if people step down]?* I don't think this question has been solved by any hospex network. BeWelcome gets closest, but the voting and the discussions can hardly be called "beautiful" and if the only active tech person would step down the path forward is not clear at all.

So we decided we will try to take small (software) steps to reduce reliance on very specific individuals (ourselves), give more control to users and enable the creation of other gift/sharing economy applications. And if we are successful we will become a small part of a much bigger active community of already 100s of software projects.

**Comment by zweifeln** [comment]
It pains me to see the community disappear.

You send out e-mails asking for help. So I made a very central point. 
You're shutting me down and wanna talk tech - that no one is interested in. So maybe you'll be like 10 people at the gathering in May, three weeks later, it might be you, your two friends and two other people still slightly working on it … two months later most likely no one is gonna work on anything anymore.

I quite liked Trustroots. I made some friends over it.
But if it dies, it dies. I'm sad about it. But some other protocol isn't changing anything about it.

Whether you want it or not, you are in charge of it. You make the calls and your call is to focus on tech. Okay. Have fun with it.
I've seen too many communities die over "let's have some other tool solve all the problems" debates to be enganged in another one.
I wish you all the best.

Just please don't send out e-mails asking for help if you actually don't want any help.

**Comment by guaka** [comment]
Are you interested in talking or doing?

**Comment by zweifeln** [comment]
I am actually quite interested in talking - meeting interesting people and talk with them. The very point why I'm on trustroots - or on any hospitality site.
I have a job. Actually two. At times I am working on more projects and I am certainly interested working with projects when I have the feeling the approach actually makes sense.
However I also remember being at a Brussels hackerspace in 2014 at one(?) of the first trustroots meetings. A friend back them told me about it, so I went and I think we did meet there briefly.
I didn't get more involved back then. I actually didn't believe trustroots would ever really come to live - for the same reasons that I wrote the earlier points here.
You proved me wrong. Trustroots did come to live and later I did join and make a profile and I am very grateful for the site/project/community. So you proved me wrong back there.
I do not see how focusing on code is really solving the underlying issues I see - so I don't really wanna get more involved. But if you do go that road I wish the very best and hope you actually prove me wrong again.

**Comment by guaka** [comment]
cool, good stuff, we could make it our mission statement, some ideas:

    "Challenged since 2014, proving doubters wrong every step of the way!"
    "Since 2014: Turning Skepticism into Belief, One Victory at a Time!"
    "Doubt Us? We've Been Shattering Expectations Since 2014!"
    "Defying Doubts, Exceeding Expectations – Our Journey Since 2014!"
    "From 2014 to Now: Silencing Doubters, Celebrating Successes!"
    "Rising Above Doubt: Our Legacy of Triumph Since 2014!"
    "Watch Us Prove You Wrong: A Legacy of Excellence Since 2014!"
    "Since 2014: Transforming Doubt into Achievement, One Success at a Time!"
    "Beyond Doubt: Crafting a History of Victory Since 2014!"
    "Eclipsing Doubt with Excellence, Unstoppable Since 2014!"
    "Disproving Doubters, Redefining Success Since 2014!"
    "Turning Doubt into Fuel: Our Unyielding Rise Since 2014!"
