### ISSUE TITLE
`README.md` has link to relative URL `nostr.net` which does not work (points to something at github.com). Should be `https://nostr.net/`.

### ISSUE THREAD

**Issue by dreirund** [Trustroots/nostroots#15]
In the [`README.md`](https://github.com/Trustroots/nostroots/blob/main/README.md?plain=1#L3), there is a link to `nostr.net`:

> `[https://nostr.net/](nostr.net)`

This does not work, as the link target points to the relative URL `nostr.net`. When the `README.md` is viewed just by opening [`https://github.com/Trustroots/nostroots`](https://github.com/Trustroots/nostroots), for example, it will point to [`https://github.com/Trustroots/nostroots/blob/main/nostr.net`](https://github.com/Trustroots/nostroots/blob/main/nostr.net), which does not exist.

The link target needs to be `https://nostr.net/`, not `nostr.net`.

Regards!

**Comment by chmac** [comment]
Thanks, fixed that.
