### ISSUE TITLE
Add to nostr.net

### ISSUE THREAD

**Issue by guaka** [Trustroots/nostroots#16]
Create PR for https://github.com/aljazceru/awesome-nostr

Something like: "Nostroots: Trustroots is a hospitality exchange network of 100k+ members, like couchsurfing(tm) but free and more alternative. We're nostrifying it."

Which section?

**Comment by chmac** [comment]
I'd be reluctant to add it until some part of it exists. If I were managing the awesome list I'd likely also reject the PR as not yet being awesome. But maybe I'm overthinking it. Maybe you're overthinking category choice?

**Comment by guaka** [comment]
notes.trustroots.org is a bit closer to awesome
