### ISSUE TITLE
Random thoughts from v1

### ISSUE THREAD

**Issue by chmac** [Trustroots/nostroots#2]
The prototype works. At least, you can publish a profile and some info. It doesn't have private messages. They would be next. But the underlying code already exists in nostr-tools for encrypting messages.

* How do we handle the async data flows?
  - Redux?
  - Sagas?
  - Thunks?
* Do we store data somewhere?
* Do we keep subscriptions open? There's no clear need to unsubscribe.
  - But how do we feed data into React in that case?
* Write a nostr-redux layer?
  - Dispatch actions, get data from nostr, fill redux
  - Is using the browser storage more idiomatic?
* Do we cache data in browser storage?
  - Relays seem to be pretty quick so far, maybe simplest to leave this alone for now

**Comment by guaka** [comment]
https://github.com/Trustroots/nostr-map
