### ISSUE TITLE
Research nostr based chat apps

### ISSUE THREAD

**Issue by chmac** [Trustroots/nostroots#25]
We have a basic prototype running nostr-map. One way to expand that test would be to encourage users to use their trustroots created private key on another app. For example, adding some kind of chat feature to the map which is also usable from a separate nostr app. The task here is to research which apps or projects could be a good fit for this.

Some thoughts to consider include:

- What `kind` of nostr messages does the app use?
- Does the chat app send notifications somehow? For example, if it's a mobile app versus a web app and so on.
- Do you think the app maintainers would be open to collaboration? If it's a smaller app with few users, then promotion on trustroots could be valuable to them.
- What's the culture like? Nostr in general can be very bitcoin bro heavy, which is a bad fit for trustroots. Ideally we'd find potential collaborators from the nostr space which are more culturally compatible.

**Comment by guaka** [comment]
#asknostr'ed https://primal.net/e/note1v2mjp7r4k4ltxfmly3m5ytrmu3rfek0lzmann52zw0ussus5phwqcrxdfv

1st reply: https://www.keychat.io/ which charges money for messaging, won't work for the trustroots userbase
when moneyless fork 👀

**Comment by guaka** [comment]
"0xChat is free to use, while KeyChat charges ecash to send messages, but I think you can also choose free relays" -- [water783](https://primal.net/e/note1352f8v3g3pqzdrprlsfgh2m6wg63a95atyu8wnnj9ndgvzqkfcnqu065mt)
