### ISSUE TITLE
What to put on nostr?

### ISSUE THREAD

**Issue by chmac** [Trustroots/nostroots#3]
Here's a little essay that I had thought to tell @guaka by phone!

I was thinking this morning about the nostr experiment. What can people do on it? That's the question I focused on. Replicating a poor quality copy of the current trustroots experience doesn't make a lot of sense. Folks might use it, but presumably they only use it if they're really motivated to try nostr, or just love p2p, etc. Otherwise, why bother?

Which led me to consider, what about putting something else on nostr? A few ideas came up:

1. Events, start time, end time, location, description, show events sorted by date in a given location...
2. Real time chat per circle
  - This might not be the best experience if there are no notifications
  - We could probably rig up something to send emails when people receive messages, but that will require a bunch of custom server side code I believe
3. A forum style of discussion, something where it's more expected that you won't get immediate replies so notifications won't be such an issue
4. A question & answer style site, stackoverflow but on nostr
5. Other kinds of gifts, which could be anything, shown on a map
  - The obvious challenge with this seems to be that if nobody uses it, it's kinda pointless to put a gift on it, chicken and egg problem...
6. Tour guide type recommendations, stuff that's recommended by trustrooters to see in a given location
7. Notes with locations, put any text with a location and show them all on a map
8. Expiring notes with locations, same as above but they expire after 1, 7, 30 days or something

What else?

## Thoughts

Personally, I think it makes sense not to put hospex on nostr at first.

We could also launch a simple demo without doing any trustroots integration. It just gets linked from trustroots. It might get spammed. We can see how it goes. Most likely it'll simply be ignored.

I'm leaning towards starting with simple notes and adding a location. We don't need to add any extra functionality to nostr to be able to do that. We can just designate a location field and then crack on. We can load all the data on every page view. If that becomes problematic we could react accordingly.

I'm liable to proceed with something like this unless I hear contra feedback or better ideas are proposed...

**Comment by guaka** [comment]
1. current Meet functionality is hardly used, could be just taken down and link to a nostr-meet thing as soon as nostr-meet is halfway working
2. hitchhiking signal/matrix group is active, if it somehow bridges with this it's insta-active
3. nostr notes should be readable in other apps, so this becomes less important, e.g. satellite.earth looks a bit more like reddit
4. I am guessing there's a Q/A stackoverflow quora clone already
5. yes map display stuff, also 6. 7. 8.

Questions derived from this:
a. a lot of these are all different nostr apps that could stand on their own? So better to see what people have built and are building, see how what we think is good fits into that? or at least build apps that can stand on their own
b. how to conenct other apps onto an authenticated trustroots relay? relates to at least 3. 4. 5.
c. alby is a browser extension in which you can manage your private key, and then use different apps?
d. ideally there's a way for alby (and similar apps) to authenticate with an app without giving out private key?
