### ISSUE TITLE
Create a development relay

### ISSUE THREAD

**Issue by chmac** [Trustroots/nostroots#35]
It should be easy to run one command and have a local nostr relay up and running immediately. If it saves its data in an sqlite file then it would also be easy to ship a default data set, delete data and reset everything, and so on. If somebody can figure out how to do this, it would be a great help for development.

An alternative would be to run our own publicly accessible development relay that requires authentication, so that our dev events cannot leak from the relay, but that might be more complicated to use...

**Comment by shuesken** [comment]
Basic version of this now available in https://github.com/Trustroots/nostroots/tree/main/develoment-utils/local-relay . The seed-data currently only comprises 2 events, but it's easy to expand this.
