### ISSUE TITLE
NIP-05: bob@trustroots.org

### ISSUE THREAD

**Issue by guaka** [Trustroots/nostroots#4]
- https://github.com/nostr-protocol/nips/blob/master/05.md
- https://thebitcoinmanual.com/articles/nostr-account-nip-05-verified/

Seems easy to implement early 2024:
- ~~npub field on user profile, which is not displayed initially~~
- GET https://www.trustroots.org/.well-known/nostr.json?name=bob returns appropriate JSON `"names": {   "bob": "b0635d6a9851d3aed0cd6c495b282167acf761729078d975fc341b22650b07b9"  } }`

UPDATE: better provide nsecs for everyone right away
- [ ] nsecbunkerd #17 
- [ ] .well-known/nostr.json
- [ ] show npub and NIP-05 on profiles (

probably add another section here, replace ELSEWHERE with NOSTR:
<img width="156" alt="image" src="https://github.com/Trustroots/nostroots/assets/54728/0a899675-e64a-49a1-9a76-5823c6bd7e7e">
(and NOSTR can even link to a page with apps that can use this)

**Comment by guaka** [comment]
I'd like to try to set up a NIP-05 team@trustroots.org for this npub https://primal.net/p/npub1lt6a968lk4h6yqduqnxcha628cudulgy8xk607c4xyxn6d6w6kcsmgp8hj

I used https://nostrtool.com/ to get the hex code:

faf5d2e8ffb56fa201bc04cd8bf74a3e38de7d0439ada7fb15310d3d374ed5b1

Now if we put a static file containing `{ "names": {   "team": "faf5d2e8ffb56fa201bc04cd8bf74a3e38de7d0439ada7fb15310d3d374ed5b1"  } }` at https://www.trustroots.org/.well-known/nostr.json it should work, it returns the same if `?name=team`  is added.

**Comment by chmac** [comment]
Maybe returning the same npub for `nostr.json?name=foo` is a lil tricky?

Maybe for the collective we could try to add a profile field for npub. Then we could add an API endpoint that resolves usernames into npubs and returns the appropriate JSON. Seems like quite a small change to the current codebase, but would open up nip05 options. Would lay the groundwork for simple trust verifications and so on.

**Comment by guaka** [comment]
there's progress.. continue at https://github.com/trustroots/trustroots/issues/2692
