### ISSUE TITLE
Figure out how to run a relay

### ISSUE THREAD

**Issue by chmac** [Trustroots/nostroots#43]
It seems like relays are not reliable for long term storage. That means we will need to run our own relay to be sure that our old events are kept available.

In theory, we don't want to have a completely open relay, and then amass vast quantities of events where we don't know which are important and which not. In three years time, we really want to be sure that every available hosting offer that was posted is still available. But if we have another million events mixed in with those few we care about, the problem of persistence and so on could be significantly worse. So at the very least, we want to be able to definitely tell which events we care about and which we don't, or in the best case, we only want to allow events on the relay which we care about.

Some immediate thoughts:

- If we allow remote logins then we need to accept events from anyone which are TO one of our users
- Same as above to support messaging with any arbitrary nostr user
- At first we might allow all content to be queried by anybody (so all data is public), but this might change, at some point we might want to introduce authorisation for some data

There's a notion called the "Outbox model" in nostr. We might also need to be mindful of that in thinking about what we want to do with a relay.

**Comment by guaka** [comment]
https://github.com/hoytech/strfry at relay.trustroots.org now, set up by @zrthstr
